[project]
name = "ex-0922"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "koodori8147-lgtm", email = "koodori8147@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "langchain-classic>=1.0.8",
    "langchain-huggingface>=1.2.2",
    "langchain-ollama>=1.1.0",
    "langchain-openai>=1.6.3",
    "langchain-teddynote>=0.5.4",
    "langchain-upstage>=0.7.7",
    "pinecone>=10.0.0",
    "sentence-transformers>=5.7.0",
]

[project.scripts]
ex-0922 = "ex_0922:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
